pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                bat 'test.bat'
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                    taskkill /F /IM java.exe >nul 2>&1 || exit /b 0
                    set PORT=8082
                    set DATA_DIR=data
                    start "AttendanceSystem" /B java -jar out\\attendance.jar
                '''
            }
        }

        stage('Deploy') {
    steps {
        bat '''
            powershell -Command "$p = Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like '*attendance.jar*' -and $_.Name -eq 'java.exe' }; if ($p) { $p | ForEach-Object { Stop-Process -Id $_.ProcessId -Force } }"
            set PORT=8082
            set DATA_DIR=data
            start "AttendanceSystem" /B java -jar out\\attendance.jar
        '''
    }
}
    }

    post {
        success {
            echo 'Attendance System deployed successfully!'
        }

        failure {
            echo 'Build/Test/Deployment failed.'
        }
    }
}
